### ISSUE TITLE
Does the node have a pointer to some data?

### ISSUE THREAD

**Issue by pauloangelo** [ennorehling/critbit#3]
Hi,

Commonly, in trees we have a key and a pointer to some data. As I could see in this implementation there is just the key. Is it true?

regards,

PA

**Comment by ennorehling** [comment]
That is correct, there is no data pointer as such. A trie stores a set of keys, and it's good at responding with all the keys that have a common prefix (for example, if you wanted to implement auto-complete, you could put an entire dictionary into the trie, and ask it for all words that begin with the string that the user has already typed.
Although it isn't meant to be a key/value store, you can use it as such by combining the key and value into a single string, such that the key is a prefix you search for. For example (pseudo-code):

    insert("key:value");
    results = find("key:");

It's not what it is intended for, but can still be used as a quick multimap replacement.
